if: branch !~ ^v\d
language: node_js
node_js: node
jobs:
  include:
  - dist: xenial
    after_success: node_modules/.bin/nyc report > coverage.lcov && bash <(curl -s https://codecov.io/bash) -X gcov
  - os: osx
    osx_image: xcode10.2
    script: node test/test.js
  - os: windows
    script: node test\\test.js
